# © 2024-25 Infosys Limited, Bangalore, India. All Rights Reserved.
"""
Planned Engine — LLM generates an execution plan → user confirms → execute.

The "planned" mode sits between routing and execution. It:
  1. Generates a structured DAG plan via LLM (which skills to call, in what order)
  2. Returns the plan for user confirmation (UI displays step-by-step preview)
  3. After confirmation, executes each step by calling skill_runner per skill
  4. Tracks per-step status (pending → running → done/failed/skipped)

Usage in SKILL.md:
    ---
    name: multi_domain_assistant
    execution_mode: planned
    worker_skills:
      - name: invoice
        description: "Invoice lookup, aging analysis"
      - name: payment
        description: "Payment status, clearing history"
      - name: general
        description: "General synthesis and summarization"
    max_steps: 8
    ---

Flow:
    User query → LLM generates plan → return plan for confirmation →
    User confirms (or modifies) → execute plan → return result
"""

import json
import time
import uuid
from typing import List, Dict, Any, Optional, Callable, Tuple
from dataclasses import dataclass, field

from .base import log


# ============================================================================
# Data Models
# ============================================================================

MAX_PLAN_STEPS = 10


@dataclass
class PlanStep:
    """A single step in a generated plan."""
    id: str                                    # Unique step ID
    skill_name: str                            # Which skill to call
    task: str                                  # What to tell the skill
    depends_on: List[str] = field(default_factory=list)  # Step IDs this depends on
    status: str = "pending"                    # pending | running | done | failed | skipped
    result: str = ""
    error: str = ""
    duration_ms: int = 0

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "skill_name": self.skill_name,
            "task": self.task,
            "depends_on": self.depends_on,
            "status": self.status,
            "result": self.result,
            "error": self.error,
            "duration_ms": self.duration_ms,
        }


@dataclass
class ExecutionPlan:
    """Complete plan generated by the planner LLM."""
    plan_id: str
    goal: str
    steps: List[PlanStep]
    confirmed: bool = False
    created_at: str = ""

    def to_dict(self) -> dict:
        return {
            "plan_id": self.plan_id,
            "goal": self.goal,
            "steps": [s.to_dict() for s in self.steps],
            "confirmed": self.confirmed,
            "created_at": self.created_at,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "ExecutionPlan":
        """Reconstruct plan from dict (e.g., from session state after confirmation)."""
        steps = [
            PlanStep(
                id=s["id"],
                skill_name=s["skill_name"],
                task=s["task"],
                depends_on=s.get("depends_on", []),
                status=s.get("status", "pending"),
                result=s.get("result", ""),
                error=s.get("error", ""),
                duration_ms=s.get("duration_ms", 0),
            )
            for s in data.get("steps", [])
        ]
        return cls(
            plan_id=data.get("plan_id", str(uuid.uuid4())[:8]),
            goal=data.get("goal", ""),
            steps=steps,
            confirmed=data.get("confirmed", False),
            created_at=data.get("created_at", ""),
        )


# ============================================================================
# Planner Prompt
# ============================================================================

PLANNER_PROMPT = """\
You are a plan generator for a multi-skill agent system.

## User Query
"{query}"

## Available Skills
{skills_list}

## Instructions
Generate an execution plan as JSON. Each step will be executed by calling \
the appropriate skill with the given task.

Rules:
- Each step MUST have: "id" (unique short string), "skill" (exact name from \
available skills), "task" (what to tell the skill), "depends_on" (list of step \
IDs it needs results from — use [] for independent steps).
- If multiple skills are needed, create one step per skill, then optionally a \
final synthesis step (skill="general" or any appropriate skill) that depends on \
all prior steps.
- Keep plans concise — maximum {max_steps} steps.
- Keep each task to 1-2 concise sentences. The skill already has domain expertise \
— describe WHAT to do, not HOW.
- Use {{step_id.result}} in a task to reference a prior step's output.
- Steps with no dependencies can run in parallel.

Respond with ONLY valid JSON (no markdown, no explanation):
{{"steps": [{{"id": "...", "skill": "...", "task": "...", "depends_on": [...]}}]}}
"""


MODIFY_PLAN_PROMPT = """\
You are modifying an execution plan based on user feedback.

## Original Goal
"{goal}"

## Current Plan
{current_plan_json}

## Available Skills
{skills_list}

## User's Requested Changes
"{modifications}"

## Instructions
Apply the user's modifications to the plan. You can:
- Add new steps
- Remove steps
- Reorder steps (update depends_on accordingly)
- Change a step's skill or task
- Split one step into multiple

Rules:
- Each step MUST have: "id" (unique short string), "skill" (exact name from \
available skills), "task" (what to tell the skill), "depends_on" (list of step \
IDs it needs results from — use [] for independent steps).
- Keep plans concise — maximum {max_steps} steps.
- Maintain valid dependency chains (no circular deps, don't depend on removed steps).
- Preserve step IDs where possible so the user can track changes.

Respond with ONLY valid JSON (no markdown, no explanation):
{{"steps": [{{"id": "...", "skill": "...", "task": "...", "depends_on": [...]}}]}}
"""


# ============================================================================
# Engine
# ============================================================================

class SkillPlannedEngine:
    """
    Two-phase execution: generate plan → (confirm) → execute.

    Phase 1: generate_plan() → returns ExecutionPlan for user review
    Phase 2: execute_plan() → runs confirmed plan step-by-step
    """

    def __init__(
        self,
        llm: Any,
        skill_runner: Callable,
        worker_skills: List[Dict[str, str]],
        max_steps: int = MAX_PLAN_STEPS,
        writer: Optional[Callable] = None,
    ):
        self.llm = llm
        self.skill_runner = skill_runner
        self.worker_skills = worker_skills
        self.max_steps = min(max_steps, MAX_PLAN_STEPS)
        self.writer = writer
        self._skill_names = {s["name"] for s in worker_skills}

    # ------------------------------------------------------------------
    # Phase 1: Plan Generation
    # ------------------------------------------------------------------

    async def generate_plan(self, query: str) -> ExecutionPlan:
        """
        Ask the LLM to generate an execution plan for the user's query.

        Returns an ExecutionPlan with confirmed=False. The caller should
        present this to the user for confirmation before calling execute_plan().
        """
        log.info(f"[PlannedEngine] Generating plan for: '{query[:100]}'")

        if self.writer:
            self.writer({"Node Name": "Plan Generation", "Status": "Started"})

        skills_list = "\n".join(
            f"  - {s['name']}: {s.get('description', '(no description)')}"
            for s in self.worker_skills
        )

        prompt = PLANNER_PROMPT.format(
            query=query,
            skills_list=skills_list,
            max_steps=self.max_steps,
        )

        try:
            from langchain_core.messages import HumanMessage
            if hasattr(self.llm, 'ainvoke'):
                response = await self.llm.ainvoke([HumanMessage(content=prompt)])
            else:
                response = self.llm.invoke([HumanMessage(content=prompt)])

            raw = response.content.strip()

            # Strip markdown code fences
            if raw.startswith("```"):
                import re
                raw = re.sub(r"^```[a-z]*\n?", "", raw, flags=re.MULTILINE)
                raw = re.sub(r"\n?```$", "", raw, flags=re.MULTILINE)
                raw = raw.strip()

            data = json.loads(raw)
            raw_steps = data.get("steps", [])

            # Validate and parse steps
            steps = []
            for s in raw_steps[:self.max_steps]:
                skill = s.get("skill", "")
                if skill not in self._skill_names:
                    log.warning(f"[PlannedEngine] Plan references unknown skill '{skill}' — skipping")
                    continue
                steps.append(PlanStep(
                    id=s.get("id", str(uuid.uuid4())[:6]),
                    skill_name=skill,
                    task=s.get("task", ""),
                    depends_on=s.get("depends_on", []),
                ))

            if not steps:
                log.error("[PlannedEngine] LLM generated empty plan")
                return ExecutionPlan(
                    plan_id=str(uuid.uuid4())[:8],
                    goal=query,
                    steps=[PlanStep(id="fallback", skill_name="general", task=query)],
                    created_at=time.strftime("%Y-%m-%dT%H:%M:%SZ"),
                )

            plan = ExecutionPlan(
                plan_id=str(uuid.uuid4())[:8],
                goal=query,
                steps=steps,
                confirmed=False,
                created_at=time.strftime("%Y-%m-%dT%H:%M:%SZ"),
            )

            log.info(f"[PlannedEngine] Plan generated: {len(steps)} steps")
            if self.writer:
                self.writer({"Node Name": "Plan Generation", "Status": "Completed"})

            return plan

        except (json.JSONDecodeError, AttributeError, KeyError) as e:
            log.error(f"[PlannedEngine] Plan generation failed: {e}")
            if self.writer:
                self.writer({"Node Name": "Plan Generation", "Status": "Failed"})
            # Return a single-step fallback plan
            return ExecutionPlan(
                plan_id=str(uuid.uuid4())[:8],
                goal=query,
                steps=[PlanStep(id="fallback", skill_name="general", task=query)],
                created_at=time.strftime("%Y-%m-%dT%H:%M:%SZ"),
            )

    # ------------------------------------------------------------------
    # Phase 1.5: Plan Modification
    # ------------------------------------------------------------------

    async def modify_plan(self, plan: ExecutionPlan, modifications: str) -> ExecutionPlan:
        """
        Modify an existing plan based on user feedback.

        The user can describe changes in natural language:
          - "Remove step 2"
          - "Add a step to validate results after step 3"
          - "Change step 1 to use the payment skill instead"
          - "Reorder: do step 3 first, then step 1"

        The LLM takes the current plan + modifications and returns an updated plan.

        Args:
            plan: The current ExecutionPlan to modify
            modifications: Natural language description of desired changes

        Returns:
            Updated ExecutionPlan with confirmed=False (needs re-confirmation)
        """
        log.info(f"[PlannedEngine] Modifying plan '{plan.plan_id}': {modifications[:100]}")

        if self.writer:
            self.writer({"Node Name": "Plan Modification", "Status": "Started"})

        skills_list = "\n".join(
            f"  - {s['name']}: {s.get('description', '(no description)')}"
            for s in self.worker_skills
        )

        # Serialize current plan steps for the LLM
        current_plan_json = json.dumps(
            {"steps": [{"id": s.id, "skill": s.skill_name, "task": s.task, "depends_on": s.depends_on} for s in plan.steps]},
            indent=2,
        )

        prompt = MODIFY_PLAN_PROMPT.format(
            goal=plan.goal,
            current_plan_json=current_plan_json,
            skills_list=skills_list,
            modifications=modifications,
            max_steps=self.max_steps,
        )

        try:
            from langchain_core.messages import HumanMessage
            if hasattr(self.llm, 'ainvoke'):
                response = await self.llm.ainvoke([HumanMessage(content=prompt)])
            else:
                response = self.llm.invoke([HumanMessage(content=prompt)])

            raw = response.content.strip()

            # Strip markdown code fences
            if raw.startswith("```"):
                import re
                raw = re.sub(r"^```[a-z]*\n?", "", raw, flags=re.MULTILINE)
                raw = re.sub(r"\n?```$", "", raw, flags=re.MULTILINE)
                raw = raw.strip()

            data = json.loads(raw)
            raw_steps = data.get("steps", [])

            # Validate and parse steps
            steps = []
            for s in raw_steps[:self.max_steps]:
                skill = s.get("skill", "")
                if skill not in self._skill_names:
                    log.warning(f"[PlannedEngine] Modified plan references unknown skill '{skill}' — skipping")
                    continue
                steps.append(PlanStep(
                    id=s.get("id", str(uuid.uuid4())[:6]),
                    skill_name=skill,
                    task=s.get("task", ""),
                    depends_on=s.get("depends_on", []),
                ))

            if not steps:
                log.warning("[PlannedEngine] Modification produced empty plan — keeping original")
                if self.writer:
                    self.writer({"Node Name": "Plan Modification", "Status": "Failed (empty result)"})
                return plan

            # Validate dependency references (no dangling deps)
            valid_ids = {s.id for s in steps}
            for step in steps:
                step.depends_on = [d for d in step.depends_on if d in valid_ids]

            modified_plan = ExecutionPlan(
                plan_id=plan.plan_id,  # keep same plan_id for tracking
                goal=plan.goal,
                steps=steps,
                confirmed=False,  # needs re-confirmation
                created_at=plan.created_at,
            )

            log.info(f"[PlannedEngine] Plan modified: {len(steps)} steps (was {len(plan.steps)})")
            if self.writer:
                self.writer({"Node Name": "Plan Modification", "Status": "Completed"})

            return modified_plan

        except (json.JSONDecodeError, AttributeError, KeyError) as e:
            log.error(f"[PlannedEngine] Plan modification failed: {e}")
            if self.writer:
                self.writer({"Node Name": "Plan Modification", "Status": "Failed"})
            # Return original plan unchanged
            return plan

    # ------------------------------------------------------------------
    # Phase 2: Plan Execution
    # ------------------------------------------------------------------

    async def execute_plan(self, plan: ExecutionPlan) -> Tuple[str, ExecutionPlan]:
        """
        Execute a confirmed plan step-by-step, respecting dependencies.

        Steps with no pending dependencies run in dependency-order.
        Each step's result is available to subsequent steps via {{step_id.result}}.

        Args:
            plan: A confirmed ExecutionPlan (plan.confirmed should be True)

        Returns:
            Tuple of (final_response, updated_plan_with_results)
        """
        if not plan.confirmed:
            log.warning("[PlannedEngine] Executing unconfirmed plan — marking confirmed")
            plan.confirmed = True

        log.info(f"[PlannedEngine] Executing plan '{plan.plan_id}' — {len(plan.steps)} steps")

        if self.writer:
            self.writer({"Node Name": "Plan Execution", "Status": "Started"})

        # Build dependency graph
        steps_by_id = {s.id: s for s in plan.steps}
        completed: set = set()
        failed: set = set()

        # Process steps in dependency order
        remaining = list(plan.steps)
        while remaining:
            # Find ready steps (all deps completed)
            ready = [
                s for s in remaining
                if all(d in completed for d in s.depends_on)
                and not any(d in failed for d in s.depends_on)
            ]

            # Mark steps with failed deps as skipped
            skipped = [
                s for s in remaining
                if any(d in failed for d in s.depends_on)
            ]
            for s in skipped:
                s.status = "skipped"
                s.error = f"Dependency failed: {[d for d in s.depends_on if d in failed]}"
                failed.add(s.id)
                remaining.remove(s)
                log.info(f"[PlannedEngine] Skipping step '{s.id}' — dependency failed")

            if not ready and remaining:
                # Circular dependency or all deps failed
                for s in remaining:
                    s.status = "skipped"
                    s.error = "Could not resolve dependencies"
                    failed.add(s.id)
                break

            if not ready:
                break

            # Execute ready steps sequentially (preserves ordering)
            for step in ready:
                await self._execute_step(step, steps_by_id, completed)
                remaining.remove(step)

                if step.status == "done":
                    completed.add(step.id)
                else:
                    failed.add(step.id)

        if self.writer:
            self.writer({"Node Name": "Plan Execution", "Status": "Completed"})

        # Synthesize final response
        final_response = await self._synthesize(plan)
        return final_response, plan

    async def _execute_step(
        self, step: PlanStep, all_steps: Dict[str, PlanStep], completed: set
    ) -> None:
        """Execute a single plan step via skill_runner."""
        step.status = "running"

        if self.writer:
            self.writer({"Node Name": f"[Plan] {step.id}: {step.skill_name}", "Status": "Started"})

        log.info(f"[PlannedEngine] Executing step '{step.id}' → skill '{step.skill_name}'")

        # Resolve {{step_id.result}} references in the task
        task = step.task
        for dep_id in step.depends_on:
            if dep_id in all_steps:
                dep_step = all_steps[dep_id]
                placeholder = f"{{{{{dep_id}.result}}}}"
                if placeholder in task:
                    task = task.replace(placeholder, dep_step.result or "")

        start = time.time()
        try:
            result = await self.skill_runner(step.skill_name, task)
            step.duration_ms = int((time.time() - start) * 1000)
            step.result = str(result)
            step.status = "done"

            log.info(f"[PlannedEngine] Step '{step.id}' completed in {step.duration_ms}ms")
            if self.writer:
                self.writer({"Node Name": f"[Plan] {step.id}: {step.skill_name}", "Status": "Completed"})

        except Exception as e:
            step.duration_ms = int((time.time() - start) * 1000)
            step.error = str(e)
            step.status = "failed"

            log.error(f"[PlannedEngine] Step '{step.id}' failed: {e}")
            if self.writer:
                self.writer({"Node Name": f"[Plan] {step.id}: {step.skill_name}", "Status": "Failed"})

    # ------------------------------------------------------------------
    # Synthesis
    # ------------------------------------------------------------------

    async def _synthesize(self, plan: ExecutionPlan) -> str:
        """Final LLM call — reads all step results and produces a user-facing answer."""
        successful_steps = [s for s in plan.steps if s.status == "done"]
        if not successful_steps:
            failed_reasons = [f"{s.id}: {s.error}" for s in plan.steps if s.error]
            return f"Plan execution failed. No steps completed successfully.\n\nErrors:\n" + "\n".join(failed_reasons)

        results_text = "\n".join(
            f"  [{s.id}] {s.skill_name}: {s.result[:600]}"
            for s in successful_steps
        )

        prompt = (
            f"You completed a multi-step plan. Based on the results below, "
            f"provide a clear, complete answer to the original goal.\n\n"
            f"**Original Goal:**\n{plan.goal}\n\n"
            f"**Step Results:**\n{results_text}\n\n"
            f"Provide a comprehensive final answer. Use markdown formatting where appropriate."
        )

        try:
            from langchain_core.messages import HumanMessage
            if hasattr(self.llm, 'ainvoke'):
                response = await self.llm.ainvoke([HumanMessage(content=prompt)])
            else:
                response = self.llm.invoke([HumanMessage(content=prompt)])
            return response.content.strip()
        except Exception as e:
            log.error(f"[PlannedEngine] Synthesis failed: {e}")
            # Fallback: concatenate results
            return "\n\n".join(
                f"### {s.skill_name}\n{s.result}" for s in successful_steps
            )

    # ------------------------------------------------------------------
    # Plan Display Helpers
    # ------------------------------------------------------------------

    def format_plan_preview(self, plan: ExecutionPlan) -> str:
        """Format plan as a human-readable preview for user confirmation."""
        lines = [
            f"## Execution Plan",
            f"**Goal:** {plan.goal}",
            f"**Steps:** {len(plan.steps)}",
            f"**Plan ID:** {plan.plan_id}",
            "",
        ]

        for i, step in enumerate(plan.steps, 1):
            deps = f" (after: {', '.join(step.depends_on)})" if step.depends_on else " (independent)"
            lines.append(f"{i}. **{step.skill_name}**{deps}")
            lines.append(f"   → {step.task}")
            lines.append("")

        lines.append("---")
        lines.append("**Options:**")
        lines.append("- Reply **'confirm'** to execute this plan as-is")
        lines.append("- Reply **'reject'** to cancel")
        lines.append("- Or **describe changes** (e.g., \"remove step 2\", \"add a validation step\", \"swap step 1 and 3\")")
        return "\n".join(lines)

    def format_execution_summary(self, plan: ExecutionPlan) -> str:
        """Format a summary of plan execution results."""
        lines = ["## Plan Execution Summary\n"]
        done = sum(1 for s in plan.steps if s.status == "done")
        failed = sum(1 for s in plan.steps if s.status == "failed")
        skipped = sum(1 for s in plan.steps if s.status == "skipped")

        lines.append(f"**Total Steps:** {len(plan.steps)}")
        lines.append(f"**Completed:** {done}")
        lines.append(f"**Failed:** {failed}")
        lines.append(f"**Skipped:** {skipped}\n")

        for s in plan.steps:
            icons = {"done": "✅", "failed": "❌", "skipped": "⏭️", "pending": "⏳", "running": "🔄"}
            icon = icons.get(s.status, "❓")
            lines.append(f"{icon} **{s.id}** ({s.skill_name}) — {s.duration_ms}ms")
            if s.error:
                lines.append(f"   Error: {s.error}")
            lines.append("")

        return "\n".join(lines)
