# © 2024-25 Infosys Limited, Bangalore, India. All Rights Reserved.
from pydantic import BaseModel, Field
from typing import List



class PlanSchema(BaseModel):
    plan: List[str] = Field(..., description="List of plans to achieve the goal.")


class ResponseSchema(BaseModel):
    response: str = Field(..., description="The final response generated by the agent.")


class CriticSchema(BaseModel):
    response_quality_score: float = Field(..., description="A score between 0 and 1 indicating the quality of the response.")
    critique_points: List[str] = Field(..., description="List of points critiquing the response.")


class CanvasFormatSchema(BaseModel):
    parts: str = Field(..., description="JSON string of List of components in the canvas format")


