apiVersion: apps/v1
kind: Deployment
metadata:
  name: iaffrontend6
spec:
  replicas: 5
  selector:
    matchLabels:
      app: iaffrontend6
  template:
    metadata:
      labels:
        app: iaffrontend6
    spec:
      containers:
      - name: iaffrontend6
        image: acr10052.azurecr.io/iaffrontend:09julv3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: iaffrontend6
  annotations:
     service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: iaffrontend6
  ports:
    - port: 80
      targetPort: 80
