# © 2024-25 Infosys Limited, Bangalore, India. All Rights Reserved.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentfoundry-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agentfoundry-backend
  template:
    metadata:
      labels:
        app: agentfoundry-backend
    spec:
      containers:
        - name: agentfoundry-backend
          image: infyartifactory.jfrog.io/infyagenticrepo/agentfoundry-backend
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: agentfoundry-backend-service
spec:
  selector:
    app: agentfoundry-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
