{
 "title": "Agent Action Dashboard1",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user_id",
    "label": "User ID",
    "query": "{\"find\": \"terms\", \"field\": \"attributes.user_id\"}"
   },
   {
    "name": "session_id",
    "label": "Session ID",
    "query": "{\"find\": \"terms\", \"field\": \"attributes.session_id\"}"
   },
   {
    "name": "action_on",
    "label": "Action On",
    "query": "{\"find\": \"terms\", \"field\": \"attributes.action_on\"}"
   },
   {
    "name": "action_type",
    "label": "Action Type",
    "query": "{\"find\": \"terms\", \"field\": \"attributes.action_type\"}"
   },
   {
    "name": "user_session",
    "label": "User Session",
    "query": "{\"find\": \"terms\", \"field\": \"attributes.user_session\"}"
   },
   {
    "name": "trace_id",
    "label": "Trace ID",
    "query": "{\"find\": \"terms\", \"field\": \"attributes.trace_id\"}"
   },
   {
    "name": "severity_text",
    "label": "Severity",
    "query": "{\"find\": \"terms\", \"field\": \"severity_text\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "attributes.session_id:$session_id AND attributes.action_on:$action_on AND attributes.action_type:$action_type AND attributes.user_id:$user_id AND attributes.user_session:$user_session AND attributes.trace_id:$trace_id AND severity_text:$severity_text",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Count by Action Type (Filtered)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "attributes.action_type",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "severity_text:$severity_text \nAND attributes.session_id:$session_id\nAND attributes.action_on:$action_on\nAND attributes.action_type:$action_type\nAND attributes.trace_id:$trace_id\nAND attributes.user_id:$user_id\nAND attributes.user_session:$user_session",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Volume Over Time (Filtered)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "severity_text",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "severity_text:$severity_text \nAND attributes.session_id:$session_id\nAND attributes.action_on:$action_on\nAND attributes.action_type:$action_type\nAND attributes.trace_id:$trace_id\nAND attributes.user_id:$user_id\nAND attributes.user_session:$user_session",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Recent Errors",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 10, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "severity_text:(ERROR OR CRITICAL) AND attributes.session_id:$session_id\nAND attributes.action_on:$action_on\nAND attributes.action_type:$action_type\nAND attributes.trace_id:$trace_id\nAND attributes.user_id:$user_id\nAND attributes.user_session:$user_session\n",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}