import os
import sys
import shutil
import asyncio
from fastapi import FastAPI
from fastapi_ws_router import WSRouter
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse #FileResponse
from contextlib import asynccontextmanager
from pydantic import BaseModel
from plannermeta_inference import meta_agent_with_planner_inference, AgentInferenceRequest,PrevSessionRequest,retrive_previous_conversation
from database_creation import initialize_tables
from database_manager import get_agents_details_for_chat,delete_chat_history_by_session_id
from fastapi import FastAPI, UploadFile, File, HTTPException 

DB_URI=os.getenv("POSTGRESQL_DATABASE_URL", "")
POSTGRESQL_HOST = os.getenv("POSTGRESQL_HOST", "")
POSTGRESQL_USER = os.getenv("POSTGRESQL_USER", "")
POSTGRESQL_PASSWORD = os.getenv("POSTGRESQL_PASSWORD", "")
DATABASE = os.getenv("DATABASE", "")
 
DB_URI = os.getenv("POSTGRESQL_DATABASE_URL", "")
 
if sys.platform.startswith("win"):
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
 
@asynccontextmanager
async def lifespan(app: FastAPI):
    await initialize_tables()
    yield
 
app = FastAPI(lifespan=lifespan)
 
router = WSRouter()
 
 
origins = [
    "http://127.0.0.1:6001",
    "http://localhost:3000"
]
 
 
app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],  # Allows all methods
    allow_headers=["*"],  # Allows all headers
)

@app.post("/planner-meta-agent/get-query-response")
async def get_planner_meta_agent_response(request: AgentInferenceRequest):
    """
    Gets the response for a query using agent inference.

    Parameters:
    ----------
    request : AgentInferenceRequest
        The request body containing the query details.

    Returns:
    -------
    dict
        A dictionary containing the response generated by the agent.
    """
    response = await meta_agent_with_planner_inference(request)
    print(response)
    return response
 
 
 
@app.post("/react-agent/get-chat-history")
@app.post("/get-chat-history")
async def get_history(request: PrevSessionRequest):
    """
    Retrieves the chat history of a previous session.

    Parameters:
    ----------
    request : PrevSessionRequest
        The request body containing the details of the previous session.

    Returns:
    -------
    dict
        A dictionary containing the previous conversation history.
    """
    return await retrive_previous_conversation(request=request)

@app.get("/get-agents-details-for-chat")
async def get_agents_details():
    """
    Retrieves detailed information about agents for chat purposes.
    Returns:
    -------
    list
        A list of dictionaries containing agent details.
        If no agents are found, raises an HTTPException with status code 404.
    """
    agent_details = await get_agents_details_for_chat()
    return agent_details

@app.get('/get-models')
def get_models():
    data = ["gpt4-8k","gpt-4o-mini","gpt-4o","gpt-35-turbo","gpt-4o-2","gpt-4o-3"]
    return JSONResponse(content={"models": data})

@app.get("/new_chat/{email}")
async def new_chat(email:str):
    import uuid
    id = str(uuid.uuid4()).replace("-","_")
    session_id = "session" + "_" + id
    return session_id


# Document uploading

# Base directory for uploads
BASE_DIR = "user_uploads"

# Function to save uploaded files
def save_uploaded_file(uploaded_file: UploadFile, save_path: str):
    file_location = os.path.join(save_path, uploaded_file.filename)
    with open(file_location, "wb") as f:
        shutil.copyfileobj(uploaded_file.file, f)
    return file_location

# Function to generate file structure
def generate_file_structure(directory="user_uploads"):
    file_struct = {}
    for root, dirs, files in os.walk(directory):
        path_parts = root.split(os.sep)
        current_level = file_struct
        for part in path_parts:
            if part not in current_level:
                current_level[part] = {}
            current_level = current_level[part]
        if files:
            current_level["__files__"] = files  
    return file_struct

@app.post("/files/user-uploads/upload-file/")
async def upload_file(file: UploadFile = File(...), subdirectory: str = ""):
    if subdirectory.startswith("/") or subdirectory.startswith("\\"):
        subdirectory = subdirectory[1:]

    save_path = os.path.join(BASE_DIR, subdirectory) if subdirectory else BASE_DIR
    if not os.path.exists(save_path):
        os.makedirs(save_path)
    file_location = save_uploaded_file(file, save_path)
    return {"info": f"File '{file.filename}' saved at '{file_location}'"}

@app.get("/files/user-uploads/get-file-structure/")
async def get_file_structure():
    file_structure = generate_file_structure(BASE_DIR)
    return JSONResponse(content=file_structure)

@app.delete("/files/user-uploads/delete-file/")
async def delete_file(file_path: str):
    full_path = os.path.join(BASE_DIR, file_path)
    if os.path.exists(full_path):
        if os.path.isfile(full_path):
            os.remove(full_path)
            return {"info": f"File '{file_path}' deleted successfully."}
        else:
            raise HTTPException(status_code=400, detail="The specified path is a directory. Only files can be deleted.")
    else:
        raise HTTPException(status_code=404, detail="No such file or directory.")

@app.get('/get-version')
def get_version():
    with open(os.path.join(os.path.dirname(__file__), 'VERSION')) as f:
        return f.read().strip()

@app.delete("/react-agent/clear-chat-history")
@app.delete("/clear-chat-history")
async def clear_chat_history(request: PrevSessionRequest):
    return await delete_chat_history_by_session_id(agentic_application_id=request.agent_id, session_id=request.session_id)
